### ISSUE TITLE
Newtoki/Manatoki Error

### ISSUE THREAD

**Issue by Lucy131** [keiyoushi/keiyoushi.github.io#2]
Newtoki/Manatoki extension could not load images.
But when I try to open in web view, it loads well.
Please fix this.

First image : when I open a chapter
Second image : when I click a open in webview button on the  first image.
Third image : Click open in webview on the menu button.
Fourth image : the result of third.

Sorry for my bad English.

![Screenshot_20240215_233955_Mihon](https://github.com/keiyoushi/keiyoushi.github.io/assets/124680668/e5e9c55f-7c37-472e-addd-43ef762bc5c8)
![Screenshot_20240215_234001_Mihon](https://github.com/keiyoushi/keiyoushi.github.io/assets/124680668/6f5fe8d2-0611-42b7-ac9c-943c09defa64)
![Screenshot_20240215_234035_Mihon](https://github.com/keiyoushi/keiyoushi.github.io/assets/124680668/37f3b432-0c2e-4001-b28a-23bc5fd7f1ae)
![Screenshot_20240215_234021_Mihon](https://github.com/keiyoushi/keiyoushi.github.io/assets/124680668/701d5c1a-6fae-4115-b7e6-660fb347d795)

**Comment by TheKingTermux** [comment]
This is not an Extension Repo, please go to [here](https://github.com/keiyoushi/extensions-source) and create an issue there
